spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/cobuying?characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: 1234

